version: 0.2
phases:
  install:
    commands:
      - echo install NGINX
      - apt-get update
      - apt-get install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Configuring NGINX
artifacts:
  files:
    - /var/www/html/index.html
