version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
